### ISSUE TITLE
EYC磁束計の設置

### ISSUE THREAD

**Issue by TatsukiWashimi** [gw-pem/kagra-pem#155]
### 目的　（なぜそれをやりたいのか、）
やっと修理が終わった磁束計を、EYCに設置する。

### ToDo　(どうすればIssueをCloseできるか)
 - [x] 1. 設置、ケーブリング。信号確認(生死のみ)
 - [x] 2. filter bank, sdf更新。信号確認(絶対値)
 - [x] 3. PEM List, PEM Map, JGWdoc 更新
 - [x] 完了。Klogに投稿

### レビュー用まとめ　（ToDoが終わっているかどうか簡潔に示す）
1.
2.
3.
4.

**Comment by yokozawa1985** [comment]
IYCにて信号確認、ケーブル確保は完了。

**Comment by TatsukiWashimi** [comment]
昨日、広瀬15->Dsub-15変換ケーブルを作りました。
その時気づいたのですが、Mag-13のピン配置と広瀬15コネクタのピン配置が一部異なっており、今まで参照していたMag-13側のピン配置だとsignal groundがtest portになってしまっているようです。


[Mag-13MC-MS Cable DR3377.pdf](https://github.com/gw-pem/kagra-pem/files/3433670/Mag-13MC-MS.Cable.DR3377.pdf)
http://bartington.jp/Literaturepdf/Drawings/mag13/Mag-13MC-MS%20Cable%20DR3377.pdf

![56044091-706b0a80-5d79-11e9-9d57-8bdf4771cabc](https://user-images.githubusercontent.com/18456905/61916839-294e0180-af85-11e9-8950-681b9d36e356.png)

今回使ったものは広瀬15コネクタのピン配置に合わせました。
power groundとsignal groundがisorateされたので、ノイズが減っているかもしれません。

**Comment by TatsukiWashimi** [comment]
設置完了しました。
(EYC MAGのchannelはADCが入っていないので、IOP test portで信号確認)

 - IYC WFのportable channelで信号確認 -> OK
 - Y-end WFで信号確認 -> OK
 - ケーブリング -> OK
 - EYC boothに固定 ->  OK 
 - 信号確認 -> OK

**Comment by TatsukiWashimi** [comment]
WFは全て56をon

**Comment by TatsukiWashimi** [comment]
![IMG_3881-1600x1200](https://user-images.githubusercontent.com/18456905/61927139-96c25800-afae-11e9-80d3-04b7ffad35e7.jpeg)
![IMG_3877-1200x1600](https://user-images.githubusercontent.com/18456905/61927143-9e81fc80-afae-11e9-8c04-58c45d7222be.jpeg)
![IMG_3878-1200x1600](https://user-images.githubusercontent.com/18456905/61927153-a80b6480-afae-11e9-9809-34d10cd1e4b0.jpeg)
![IMG_3879-1200x1600](https://user-images.githubusercontent.com/18456905/61927158-af327280-afae-11e9-9d4e-8616d96c9472.jpeg)

**Comment by TatsukiWashimi** [comment]
あとはadc modelの設定とfilter bankの設定

**Comment by TatsukiWashimi** [comment]
modelの編集を行った。

before
![Screenshot 2019-07-28 at 15 32 34](https://user-images.githubusercontent.com/18456905/62003214-d162f680-b14e-11e9-9491-81e5e2e4fcd3.png)

after
![Screenshot 2019-07-28 at 15 37 31](https://user-images.githubusercontent.com/18456905/62003217-db84f500-b14e-11e9-9293-067b02029e8c.png)

startk1pemey0 までやった。
今日の夕方に奥富君がDAQ restartするそうなので、それ以降適応される。

**Comment by TatsukiWashimi** [comment]
PEM List 更新完了
![Screenshot 2019-07-28 at 15 52 57](https://user-images.githubusercontent.com/18456905/62003281-c6f52c80-b14f-11e9-9098-b87ab17de7d6.png)

**Comment by TatsukiWashimi** [comment]
DAQ restartされたもよう
![無題](https://user-images.githubusercontent.com/18456905/62006846-523ae600-b181-11e9-907c-8564e3b17130.png)
何故か絶対値よりもX成分の方が大きい。要確認
