### ISSUE TITLE
旧pemプロジェクトからの移行

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-pem/kagra-pem#2]
今後のPEMのプロジェクトはgw-pemで行うことにする。

Detchar配下にあった昔のIssueをgw-pemに移す。

なので関係者には、昔のIssueをCloseするか、gw-pemに以降するかしてほしい。

- [x] https://github.com/gw-analysis/detector-characterization/issues/97, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/96, move to gw-pem (moved)
- [x] https://github.com/gw-analysis/detector-characterization/issues/95, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/94, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/93, move to gw-pem (moved)
- [x] https://github.com/gw-analysis/detector-characterization/issues/92, move to gw-pem (moved)
- [x] https://github.com/gw-analysis/detector-characterization/issues/91, move to gw-pem (moved)
- [x] https://github.com/gw-analysis/detector-characterization/issues/90, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/89, moved (KN)
- [x] https://github.com/gw-analysis/detector-characterization/issues/88, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/87, closed (KN)
- [x] https://github.com/gw-analysis/detector-characterization/issues/86, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/85, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/84, moved with update (KN)
- [x] https://github.com/gw-analysis/detector-characterization/issues/83, moved with update (KN)
- [x] https://github.com/gw-analysis/detector-characterization/issues/82, closed (KN)
- [x] https://github.com/gw-analysis/detector-characterization/issues/81 moved with update (KN)
- [x] https://github.com/gw-analysis/detector-characterization/issues/80 moved (KN)
- [x] https://github.com/gw-analysis/detector-characterization/issues/79, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/77
- [x] https://github.com/gw-analysis/detector-characterization/issues/76, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/75, moved (KN)
- [x] https://github.com/gw-analysis/detector-characterization/issues/74, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/72, closed (KN)
- [x] https://github.com/gw-analysis/detector-characterization/issues/71, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/69, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/68, closed (KN)
- [x] https://github.com/gw-analysis/detector-characterization/issues/67, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/66, move to gw-pem
- [x] https://github.com/gw-analysis/detector-characterization/issues/65, moved with update (KN)
- [x] https://github.com/gw-analysis/detector-characterization/issues/64, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/63, closed (KN)
- [x] https://github.com/gw-analysis/detector-characterization/issues/57, move to gw-pem
- [x] https://github.com/gw-analysis/detector-characterization/issues/56, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/55, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/53, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/52, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/51, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/49, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/48, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/47, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/45, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/44, move to gw-pem
- [x] https://github.com/gw-analysis/detector-characterization/issues/43, closed (KN)
- [x] https://github.com/gw-analysis/detector-characterization/issues/42, closed (KN)
- [x] https://github.com/gw-analysis/detector-characterization/issues/39, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/38, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/37, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/36, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/35, moved (KN)
- [x] https://github.com/gw-analysis/detector-characterization/issues/34, moved (KN)
- [x] https://github.com/gw-analysis/detector-characterization/issues/32, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/30, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/29, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/28, closed (KN)
- [x] https://github.com/gw-analysis/detector-characterization/issues/27, closed (KN)
- [x] https://github.com/gw-analysis/detector-characterization/issues/26, closed (KN)
- [x] https://github.com/gw-analysis/detector-characterization/issues/25, moved (KN)
- [x] https://github.com/gw-analysis/detector-characterization/issues/22, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/18, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/14, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/11, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/9, closed
- [x] https://github.com/gw-analysis/detector-characterization/issues/6, closed (KN)
- [x] https://github.com/gw-analysis/detector-characterization/issues/5, closed (KN)
- [x] https://github.com/gw-analysis/detector-characterization/issues/3, closed (KN)

ふう…。めちゃくちゃ溜まってる…。

ラベルの意味は以下の通り。
* ”closed” ：三代が独断で今日closeしたもの。
* “move to gw-pem” ：三代が独断でgw-pemに以降するもの。あとでgw-pemに新規Issueとしてつくる。

**Comment by koji-n** [comment]
権限がないので編集できない
closed: 97, 95, 94
move to gw-pem: 96, 93, 92
To be discussed: 91
ちなみに、「以降」ではない。
91まで完了。後で89から再開

**Comment by koji-n** [comment]
closed: 87, 82, 72, 68, 63, 43, 42, 28, 27, 26, 6, 5, 3
move to gw-pem: 89, 84, 83, 81, 80, 75, 35, 34, 25
to be discussed: 77, 65, 37
とりあえず全部見た。

**Comment by MiyoKouseki** [comment]
横澤さんもこのリポジトリに参加したのでアサインしました。

**Comment by yokozawa1985** [comment]
長野さん、三代さんの整理が完了したら僕の方でも見ていきます。

**Comment by neouniverse** [comment]
ここで良いのか分かりませんが過去に作って今はいらなくなったチャンネルを掃除して欲しい。

例) K1:PEM-EXA_PDA1_DC_IN1.DQ
そもそもPEMじゃない。多分当時は時間がなくてとりあえずPEMに入れたんだと思うけど
"top names"使えばPEMモデル内でもK1:AOS(?)とか別の名前をつけられる。

その他brucoのexclude/incudeにpem関連チャンネルを入れるときに思った事
K1:PEM-の次に来るワードに同列のものと思えないものが混じっている
K1:PEM-EXA_ -> チェンバーの名前
K1:PEM-EXV_ -> 防振室の名前
K1:PEM-EX_ -> エリアの名前
これも過去の遺物が残っているだけかもしれないけどEXはEXA, EXV, EX0(ラック名)等を内包するので
センサー設置に絡んでない人からすると違いは？という感じになる。

似たような事で
K1:PEM-EX_*_TMS*
があるかと思えば
K1:PEM-TMSX_*
などもある。

**Comment by koji-n** [comment]
ほとんどのものは処理しました。

gw-analysis/detector-characterization#65 についてはよくわからないので、適当にしました。
誰かコンタクトを取ってみてください。

gw-analysis/detector-characterization#77　と　gw-analysis/detector-characterization#37 も分からないのでおいてあります。多分 @MiyoKouseki  マター。

**Comment by MiyoKouseki** [comment]
完了。Close
