### ISSUE TITLE
センサー設置用のフレームの用意

### ISSUE THREAD

**Issue by koji-n** [gw-pem/kagra-pem#60]
### 目的　（なぜそれをやりたいのか、）
センサーは置き方によっては雑音が混入する。
それを防ぐような設置用フレームを作成する。

### ToDo　(どうすればIssueをCloseできるか)
 - [ ] 1. どのセンサーに必要か考える
 - [ ] 2. 設計する
 - [ ] 3. テスト
完了

### レビュー用まとめ　（ToDoが終わっているかどうか、図やWikiのリンク等で簡潔に示す）
1.
2.
3.
4.

**Comment by yokozawa1985** [comment]
定盤直置きが影響しているのかは来週チェックしてみます。
チェンバーへの設置に関する議論は鷲見さん中心に開始できたらと思います。

**Comment by MiyoKouseki** [comment]
10日が経ちました。
どうですか？

**Comment by yokozawa1985** [comment]
スペクトルだけでもとってみます。

**Comment by MiyoKouseki** [comment]
”Good first issue”ラベルをつけて New commers のテーマとして放置しませんか。

**Comment by yokozawa1985** [comment]
常磐直置きの影響は測定しました。
/users/yokozawa/190123
しかし、三代さんがおっしゃっている通り、New commers issueにしましょう。

磁束計は鷲見さんがやってくださっていて
マイクは、T田中さんがやりかけている。
あとは加速度計。
書いていきます。

**Comment by yokozawa1985** [comment]
磁束計の設置方法

- [ ] マイクスタンド測定と手持ちでノイズレベルが変わるのか？

- [ ] プラスチック、ゴム、塩ビ等を用いると金属の固定器具に比べて変化が現れるのか？

- [ ] 最終的に、ラックの裏への設置を考えた場合にどのような固定器具を選択するのか(影響がほとんどないレベルのノイズに抑えられるのか？)

**Comment by yokozawa1985** [comment]
マイクの設置方法

- [ ] 定盤では、上からぶら下げる方式を基本的にはとっているが、ミニマイクスタンドの方が良いのか、定盤や壁に貼り付けるのがいいのか、全く別の方法を考案した方がいいのかを調べる

- [ ] クリーンエリアの床からぶら下げるのが良いのか、別のもの(例えばハシゴとか)にぶら下げるのが良いのか、マイクスランドをいちいち用意するのが良いのか？観測帯域に共振を持たない棒を設置するのが良いのか、

**Comment by yokozawa1985** [comment]
加速度計の設置方法

- [ ] 定盤ではイモネジ固定が良いのか、長野さん設計のL字金具を挟むのが良いのか

- [ ] チャンバーの固定具(まだ全く議論が始まっていないので議題を作るところから)

**Comment by yokozawa1985** [comment]
地震計は地面直置きでないとダメな気がする。。

**Comment by yokozawa1985** [comment]
RFアンテナ

T田中さんが神岡に戻って来てから考える。

**Comment by yokozawa1985** [comment]
close
